# Form implementation generated from reading ui file 'MOTOR_TEST_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 291)
        Form.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.BATTERY_STATE = QtWidgets.QGroupBox(parent=Form)
        self.BATTERY_STATE.setGeometry(QtCore.QRect(670, 30, 181, 221))
        self.BATTERY_STATE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BATTERY_STATE.setObjectName("BATTERY_STATE")
        self.TEMP_READOUT = QtWidgets.QLCDNumber(parent=self.BATTERY_STATE)
        self.TEMP_READOUT.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.TEMP_READOUT.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.TEMP_READOUT.setObjectName("TEMP_READOUT")
        self.VOLTAGE_READOUT = QtWidgets.QLCDNumber(parent=self.BATTERY_STATE)
        self.VOLTAGE_READOUT.setGeometry(QtCore.QRect(10, 90, 101, 41))
        self.VOLTAGE_READOUT.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.VOLTAGE_READOUT.setObjectName("VOLTAGE_READOUT")
        self.CURRENT_READOUT = QtWidgets.QLCDNumber(parent=self.BATTERY_STATE)
        self.CURRENT_READOUT.setGeometry(QtCore.QRect(10, 160, 101, 41))
        self.CURRENT_READOUT.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.CURRENT_READOUT.setObjectName("CURRENT_READOUT")
        self.TEMP_LABEL = QtWidgets.QLabel(parent=self.BATTERY_STATE)
        self.TEMP_LABEL.setGeometry(QtCore.QRect(120, 30, 47, 20))
        self.TEMP_LABEL.setObjectName("TEMP_LABEL")
        self.CURR_LABEL = QtWidgets.QLabel(parent=self.BATTERY_STATE)
        self.CURR_LABEL.setGeometry(QtCore.QRect(120, 170, 47, 20))
        self.CURR_LABEL.setObjectName("CURR_LABEL")
        self.VOLT_LABEL = QtWidgets.QLabel(parent=self.BATTERY_STATE)
        self.VOLT_LABEL.setGeometry(QtCore.QRect(120, 100, 47, 20))
        self.VOLT_LABEL.setObjectName("VOLT_LABEL")
        self.MODE = QtWidgets.QGroupBox(parent=Form)
        self.MODE.setGeometry(QtCore.QRect(480, 30, 161, 111))
        self.MODE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MODE.setObjectName("MODE")
        self.QUIET = QtWidgets.QRadioButton(parent=self.MODE)
        self.QUIET.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.QUIET.setObjectName("QUIET")
        self.LOUD = QtWidgets.QRadioButton(parent=self.MODE)
        self.LOUD.setGeometry(QtCore.QRect(10, 60, 131, 17))
        self.LOUD.setObjectName("LOUD")
        self.MOTOR_SPEED = QtWidgets.QGroupBox(parent=Form)
        self.MOTOR_SPEED.setGeometry(QtCore.QRect(30, 30, 421, 171))
        self.MOTOR_SPEED.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MOTOR_SPEED.setObjectName("MOTOR_SPEED")
        self.STARTGEN = QtWidgets.QSlider(parent=self.MOTOR_SPEED)
        self.STARTGEN.setGeometry(QtCore.QRect(40, 40, 191, 22))
        self.STARTGEN.setStyleSheet("selection-color: rgb(0, 85, 0);\n"
"selection-background-color: rgb(0, 170, 0);")
        self.STARTGEN.setSingleStep(1)
        self.STARTGEN.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.STARTGEN.setObjectName("STARTGEN")
        self.ICEEMULATOR = QtWidgets.QSlider(parent=self.MOTOR_SPEED)
        self.ICEEMULATOR.setGeometry(QtCore.QRect(40, 120, 191, 22))
        self.ICEEMULATOR.setAutoFillBackground(False)
        self.ICEEMULATOR.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ICEEMULATOR.setObjectName("ICEEMULATOR")
        self.STARTGEN_LABEL = QtWidgets.QLabel(parent=self.MOTOR_SPEED)
        self.STARTGEN_LABEL.setGeometry(QtCore.QRect(180, 10, 121, 20))
        self.STARTGEN_LABEL.setObjectName("STARTGEN_LABEL")
        self.icelabel = QtWidgets.QLabel(parent=self.MOTOR_SPEED)
        self.icelabel.setGeometry(QtCore.QRect(190, 100, 81, 20))
        self.icelabel.setObjectName("icelabel")
        self.STARTGEN_READOUT = QtWidgets.QLCDNumber(parent=self.MOTOR_SPEED)
        self.STARTGEN_READOUT.setGeometry(QtCore.QRect(290, 40, 101, 31))
        self.STARTGEN_READOUT.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"\n"
"")
        self.STARTGEN_READOUT.setSmallDecimalPoint(False)
        self.STARTGEN_READOUT.setDigitCount(5)
        self.STARTGEN_READOUT.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.STARTGEN_READOUT.setProperty("value", 0.0)
        self.STARTGEN_READOUT.setProperty("intValue", 0)
        self.STARTGEN_READOUT.setObjectName("STARTGEN_READOUT")
        self.ICE_READOUT = QtWidgets.QLCDNumber(parent=self.MOTOR_SPEED)
        self.ICE_READOUT.setGeometry(QtCore.QRect(290, 110, 101, 31))
        self.ICE_READOUT.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"")
        self.ICE_READOUT.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.ICE_READOUT.setProperty("value", 0.0)
        self.ICE_READOUT.setObjectName("ICE_READOUT")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BATTERY_STATE.setTitle(_translate("Form", "BATTERY STATE"))
        self.TEMP_LABEL.setText(_translate("Form", "DEG"))
        self.CURR_LABEL.setText(_translate("Form", "AMPS"))
        self.VOLT_LABEL.setText(_translate("Form", "VOLTS"))
        self.MODE.setTitle(_translate("Form", "MODE"))
        self.QUIET.setText(_translate("Form", "Quiet (BATT ONLY)"))
        self.LOUD.setText(_translate("Form", "Loud (ICE CHARGING)"))
        self.MOTOR_SPEED.setTitle(_translate("Form", "MOTOR SPEED"))
        self.STARTGEN_LABEL.setText(_translate("Form", "STARTER/GENERATOR"))
        self.icelabel.setText(_translate("Form", "ICE EMULATOR"))
